enabled = true
anchor = "BOTTOM"
side = "LEFT"
offsetX = 0
offsetY = 0
style = "ROUNDED_CORNERS"
orientation = "VERTICAL"
widgetShown = "NOT_EMPTY"
offhandSlotBehavior = "ALWAYS_LEAVE_SPACE"
durabilityDisplay = "NUMERIC"
pushBossbars = true
pushStatusEffectIcons = true
pushSubtitles = true
reversed = false
iconsShown = true
warningShown = true
playBreakSound = true
minDurabilityValue = 20
minDurabilityPercentage = 0.23
warningBobIntensity = 3
